### Exercise Basic Algebra scratches

In [1]:
# imports
import numpy as np
import matplotlib as mlp

#### Functions in Python

It's good to write code based on conventions and best practices
Code is written for the people, not for the compiler. 
When we write in groups, we should tend to make sure the code will look as if written by a single person.
Style, conventions, best practices.
Python is multi-paradigm language
functional, OOP
A function depends only on its parameters
A function should do its work, to return a value or throw an error.


In [5]:
def get_numbers(low, high):
    return list(range(low, high))

In [8]:
numbers = get_numbers(1, 11)

In [18]:
numbers

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [13]:
mapped_numbers = list(map(lambda n: n + 2, numbers))

In [20]:
mapped_numbers

[3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [15]:
list(filter(lambda n: n < 5, mapped_numbers))

[3, 4]

In [17]:
[(n + 2) ** 2 for n in numbers if (n < 7) and (n ** 2 >= 25)]

[49, 64]

Closure in Python

In [21]:
def summator(a):
    def inner_summator(b):
        return a + b
    return inner_summator

In [22]:
add5 = summator(5)

In [23]:
add5(10)

15

In [24]:
[add5(n) for n in numbers]

[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [25]:
[summator(10)(n) for n in numbers]

[11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

Libraries:
itertools, functools, toolz
functional programming.

lambda calculus - λ-calculus

In [27]:
np.arange(20) > 10

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [29]:
np_nums = np.arange(20)
np_nums

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [30]:
np_nums[np_nums>3] * 2

array([ 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [31]:
np_nums * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

y = f(x)

Iterative vs. recursive method.

#### Functions in Math

Maths conventions - we can reuse the results


Interpolation.
y = f(x) ==> we assume that y depends on x
we assume that f is a minimalistic polynomial 
Interpolation is within the known values, outside is Extrapolation. Extrapolation could be dangerous.
System which with small differences in the entrance lead to huge differences on the exit are *chaotic*.